version: "3"

volumes:
  satisdiscordstatusbot:

services:
   satisfactorydiscordstatusbot:
      image: soulinferno/satisfactoryserverdiscordbotgerman
      restart: always
      container_name: satisfactorydiscordstatusbotgerman
      command: node ./dist/index.js
      volumes:
#           Pfadangabe ist verpflichtend. Bitte auf die selbsterstellte .env Datei ändern
        - /volume1/server/SatisfactoryDiscordBot/.env:/home/node/app/config/.env
